### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-js-arrays#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://enthusiastic-locket.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/js-arrays/1) criteria:
- [x] The current number of todo items is always displayed below the list of todos.
- [x] A "Clear all" button exists, which will clear all todos when clicked.
- [x] A "Can't decide!" button exists, which picks a random todo item and shows it to the user in an alert.
- [x] Each todo item contains two additional buttons: "↑" and "↓", which move the item up or down in the list, respectively. If the item is already at the top or bottom, then the button to move it further up or down, respectively, should not appear.

**Comment by KatieMFritz** [comment]
@chrisvfritz!

**Comment by chrisvfritz** [comment]
:shipit:! See [this issue](https://github.com/KatieMFritz/codelab-js-objects/issues/3) for tips for the future.
